# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_photos', models.CharField(max_length=500)),
                ('album_next_goal', models.IntegerField()),
                ('album_created_at', models.DateTimeField()),
                ('album_updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_key', models.CharField(max_length=500)),
                ('configuration_value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=500)),
                ('photo_https_url', models.CharField(max_length=500)),
                ('photo_hashtags', models.CharField(max_length=500)),
                ('photo_user', models.CharField(max_length=500)),
                ('photo_user_name', models.CharField(max_length=500)),
                ('photo_likes', models.IntegerField()),
                ('photo_post_id', models.BigIntegerField()),
                ('photo_hash', models.CharField(max_length=1024)),
                ('photo_created_at', models.DateTimeField()),
                ('photo_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cron.Album')),
            ],
        ),
    ]
